{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "QTI item creation API"
    },
    "schemes": [
        "http",
        "https"
    ],
    "paths": {
        "/taoQtiItem/RestQtiItem/import/": {
            "post": {
                "description": "Import QTI item entry point from uploaded package\nCheck POST method & get valid uploaded file\n",
                "parameters": [
                    {
                        "name": "content",
                        "in": "formData",
                        "description": "file attachemnt zip format supported",
                        "required": true,
                        "type": "file"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                           "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "data": {
                                    "$ref" : "#/definitions/data"
                                }
                            } 
                            
                        },
                        "examples": {
                            "application/json": {
                                "success": true,
                                "data": {
                                    "items": [
                                        "http://tao.local/mytao.rdf#xxxxxxxxxxxxx1",
                                        "http://tao.local/mytao.rdf#xxxxxxxxxxxxx2",
                                        "http://tao.local/mytao.rdf#xxxxxxxxxxxxx3",
                                        "http://tao.local/mytao.rdf#xxxxxxxxxxxxx4"
                                        ]
                                },
                                "version": "3.1.0"
                            }
                        }
                    },
                    "400": {
                        "description": "bad request if you send invalid parameters",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 0,
                                "errorMsg": "At least one mandatory parameter was required but found missing in your request",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized Supplied credentials are not valid"
                    },
                    "403": {
                        "description": "user isn't authorized to access to this resource"
                    },
                    "500": {
                        "description": "Internal error (should not occur)",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 0,
                                "errorMsg": "Exception error description",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    },
                    "501": {
                        "description": "not implemented if you call this API with GET method",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 501,
                                "errorMsg": "Only post method is accepted to import Qti package.",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/taoQtiItem/RestQtiItem/createQtiItem/": {
            "post": {
                "description": "Create an empty QTI item\n",
                "parameters": [
                    {
                        "name": "label",
                        "in": "formData",
                        "description": "Item Label",
                        "required": true,
                        "type": "string",
                        "format": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "examples": {
                            "application/json": {
                                "success": true,
                                "data": "http://tao.local/mytao.rdf#xxxxxxxxxxxxx",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "true on success"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "data": {
                                    "type": "string",
                                    "description": "item uri"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "bad request if you send invalid parameters",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 0,
                                "errorMsg": "At least one mandatory parameter was required but found missing in your request",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized Supplied credentials are not valid"
                    },
                    "403": {
                        "description": "user isn't authorized to access to this resource"
                    },
                    "500": {
                        "description": "Internal error (should not occur)",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 0,
                                "errorMsg": "Exception error description",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    },
                    "501": {
                        "description": "not implemented if you call this API with GET method",
                        "examples": {
                            "application/json": {
                                "success": false,
                                "errorCode": 501,
                                "errorMsg": "Only post method is accepted to import Qti package.",
                                "version": "3.1.0"
                            }
                        },
                        "schema": {
                            "title": "response",
                            "format": "json",
                            "type": "object",
                            "properties": {
                                "success": {
                                    "type": "boolean",
                                    "description": "false on failure"
                                },
                                "version": {
                                    "type": "string"
                                },
                                "errorCode": {
                                    "type": "integer",
                                    "description": "error code"
                                },
                                "errorMsg": {
                                    "type": "string",
                                    "description": "error description"
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    "definitions": {
        "data" : {
            "type": "object",
            "description": "output user data",
            "properties": {
                "items": {
                   "type": "array",
                   "items": {
                      "type": "string"
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "taoQtiItem on Github",
        "url": "https://github.com/oat-sa/extension-tao-itemqti"
    }
}